package dev.jianastrero.journey.example

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.tooling.preview.Preview
import dev.jianastrero.journey.example.screens.DoneScreen
import dev.jianastrero.journey.example.screens.EnterEmailScreen
import dev.jianastrero.journey.example.screens.EnterPasswordScreen

@Composable
@Preview
fun App() {
    MaterialTheme {
        // LoginStepJourneyHost, LoginStepView, and the per-step controller interfaces
        // are all generated by KSP from the @Journey annotation on LoginStep.
        // Drop the host where the journey starts; handle each screen state in the `when` block.
        LoginStepJourneyHost(onFinish = { /* journey complete — navigate to home, restart, etc. */ }) { view ->
            // `view` is a sealed class — the compiler enforces exhaustiveness.
            // Each branch receives a typed controller exposing only the valid exits for that step.
            when (view) {
                is LoginStepView.EnterEmail ->
                    EnterEmailScreen(view.controller)

                // view.step holds the data class fields forwarded from the previous step.
                is LoginStepView.EnterPassword ->
                    EnterPasswordScreen(view.step.email, view.controller)

                is LoginStepView.Done ->
                    DoneScreen(view.controller)
            }
        }
    }
}
